site_name: 'Drush Commands'
site_author: 'Moshe Weitzman'
repo_name: GitHub
repo_url: 'https://github.com/drush-ops/drush'
edit_uri: ''
theme:
  name: readthedocs
extra:
  version: '1.0'
site_url: 'http://commands.drush.org'
markdown_extensions:
  -
    toc:
      toc_depth: 0
      permalink: true
  -
    admonition: {  }
nav:
  -
    _global:
      - browse.md
      - deploy.md
      - drupal_directory.md
      - generate.md
      - help.md
      - jn_get.md
      - list.md
      - runserver.md
      - updatedb.md
      - updatedb_status.md
      - version.md
  -
    cache:
      - cache_clear.md
      - cache_get.md
      - cache_rebuild.md
      - cache_set.md
      - cache_tags.md
  -
    config:
      - config_delete.md
      - config_edit.md
      - config_export.md
      - config_get.md
      - config_import.md
      - config_pull.md
      - config_set.md
      - config_status.md
  -
    core:
      - core_cron.md
      - core_edit.md
      - core_init.md
      - core_requirements.md
      - core_rsync.md
      - core_status.md
      - core_topic.md
  -
    deploy:
      - deploy_hook.md
      - deploy_hook-status.md
  -
    entity:
      - entity_delete.md
      - entity_updates.md
  -
    image:
      - image_derive.md
      - image_flush.md
  -
    locale:
      - locale_check.md
      - locale_export.md
      - locale_import.md
      - locale_update.md
  -
    php:
      - php_cli.md
      - php_eval.md
      - php_script.md
  -
    pm:
      - pm_enable.md
      - pm_list.md
      - pm_security.md
      - pm_uninstall.md
  -
    queue:
      - queue_delete.md
      - queue_list.md
      - queue_run.md
  -
    role:
      - role_create.md
      - role_delete.md
      - role_list.md
      - role_perm_add.md
      - role_perm_remove.md
  -
    site:
      - site_alias.md
      - site_alias-convert.md
      - site_install.md
      - site_set.md
      - site_ssh.md
  -
    sql:
      - sql_cli.md
      - sql_connect.md
      - sql_create.md
      - sql_drop.md
      - sql_dump.md
      - sql_query.md
      - sql_sanitize.md
      - sql_sync.md
  -
    state:
      - state_delete.md
      - state_get.md
      - state_set.md
  -
    theme:
      - theme_enable.md
      - theme_uninstall.md
  -
    twig:
      - twig_compile.md
      - twig_unused.md
  -
    user:
      - user_block.md
      - user_cancel.md
      - user_create.md
      - user_information.md
      - user_login.md
      - user_password.md
      - user_role_add.md
      - user_role_remove.md
      - user_unblock.md
  -
    views:
      - views_analyze.md
      - views_dev.md
      - views_disable.md
      - views_enable.md
      - views_execute.md
      - views_list.md
  -
    watchdog:
      - watchdog_delete.md
      - watchdog_list.md
      - watchdog_show.md
      - watchdog_show-one.md
