version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
jobs:
  placeholder:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - placeholder
          # The filter makes the workflow look like an error so lets omit it.
          # filters:
          #   branches:
          #     only: not-happenning
